### ISSUE TITLE
Update OAuth scopes

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#143]
The Mastodon OAuth Scopes page specifies additional scopes for `push` and admin related scopes. We should at least provide these scopes as well:

- `push`

The `follow` scope has been deprecated in Mastodon 3.5.0 and we should mark it eventually. Users should start to request `read` and/or `write` scope instead.

The admin scopes `admin:read` and `admin:write` can be left aside for the moment, as we do not implement any of the admin calls yet.

**Comment by bocops** [comment]
I'd like to do this, including the addition of both admin scopes and all child scopes and also the deprecation of our definition of `FOLLOW`.

Regarding our definition of `ALL(Scope(READ, WRITE, FOLLOW).toString())`, this is currently a convoluted way of defining `ALL.scopeName` as `read write follow`. Instead of changing this definition to something like `read write push`, I think it would be sensible to just deprecate this one as well, while keeping its scopeName as currently defined. In the future, this should be removed with `FOLLOW`.

Reason: Redefining `ALL` might lead to hard-to-detect errors, for example if a library user has previously used that scope for app creation but not yet in a specific authorization request. According to [Mastodon documentation about OAuth scopes](https://docs.joinmastodon.org/api/oauth-scopes/#oauth-scopes):
> The set of scopes saved during app creation must include all the scopes that you will request in the authorization request, otherwise authorization will fail.

In the future, anyone requesting full access should just do this by something like `Scope(READ, WRITE, PUSH)` directly.

Any objections?

**Comment by bocops** [comment]
Also marking this as necessary for 2.0.0. We do have some admin methods by now, but lack the possibility for users to declare the scopes necessary to access them.
