### ISSUE TITLE
When the maven image will be updated ?

### ISSUE THREAD

**Issue by vvvlll93** [andregasser/bigbone#292]
Hi,

First, thanks to all of you for your amazing work with Bigbone.

We implemented it and it works like a charm.

One question : we saw that you recently implemented the full list of parameters for the searchContent method, allowing to use pagination. We're using the maven source, but the last update is the 2 september.

When will it be updated, and include the full list of parameters for the searchContent method ?

**Comment by andregasser** [comment]
Hello @vvvlll93 

Great to hear that you enjoy using BigBone. 

Currently the [Hacktoberfest](https://www.hacktoberfest.com) is still running. Due to this, lots of changes are integrated, which also have to be tested at some point. My plan is to release a new snapshot at the beginning of November. This will then also include the search improvements.

I hope that I have answered your question. Otherwise just contact me again if you have any questions.

**Comment by vvvlll93** [comment]
Perfect ! Thanks a lot 😊 And keep up the good work !
