### ISSUE TITLE
Rework Follows.kt

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#57]
`Follows.postRemoteFollow()` currently posts to `/api/v1/follows` and returns an `Account`. Does this actually do anything?

Closest I could find in Mastodon API is the endpoint `/api/v1/accounts/:id/follow` returning a `Relationship`. Is that what we actually want to do here, or am I missing something obvious?

[https://docs.joinmastodon.org/methods/accounts/#follow](https://docs.joinmastodon.org/methods/accounts/#follow)

**Comment by bocops** [comment]
The latter functionality already exists as `Accounts.postFollow()`, so maybe this `Follows` class can just be removed?

**Comment by andregasser** [comment]
I'll have a look too.

**Comment by andregasser** [comment]
A couple of days ago, I went through all the documented API endpoints on the Mastodon site and documented them in [API.md](https://github.com/andregasser/bigbone/blob/master/API.md) in order to get a better overview of whats missing from an implementation perspective. `/api/v1/follows` is one of the endpoints that I did not find during that research. It's not officially documented. 

I assume it has been deprecated in the Mastodon server the past in favor of `/api/v1/accounts/:id/follow` and then later, was removed entirely. 

So from my side it's fine if we just remove it entirely as well (incl. samples and tests).
