### ISSUE TITLE
Removed endpoint used by Public.getSearch()

### ISSUE THREAD

**Issue by bocops** [andregasser/bigbone#58]
`Public.getSearch()` uses the endpoint `/api/v1/search` which has been [removed since Mastodon 3.0.0](https://docs.joinmastodon.org/methods/search/#v1). V2 endpoint needs to be used instead.

**Comment by bocops** [comment]
Since this endpoint is not only deprecated as others, but completely removed, I believe this needs to be considered a bug that should be fixed for 2.0.0.

**Comment by andregasser** [comment]
Yes, that `/v1/search` endpoint will fail if called, so we should not offer it to our users like that. The least we need to do is to remove it. But searching is an important feature on social media, so it would be super cool, if we could ship a working implementation in the 2.0.0 release. I also like the new v2 endpoint because it searches for hashtags (which was newly introduced by Mastodon in the 4.x release).

I had a quick look at the endpoint documentation: The `v1/search` endpoint looks similar to the `v2/search` endpoint on the calling site, but the response is different. But most of the entities that are returned are already present in our code.

What about this:
We implement a working `v2/search` endpoint which returns the entities in the form we currently have. If some attributes are missing (e.g. in Account), we just ignore them for the moment (the deserializer will just ignore it). We can add them after the 2.0.0 release. This way, we can reduce the effort a bit but still deliver a search feature that works.

What do you think @bocops ?

**Comment by bocops** [comment]
Yes, offering something that works without going into too much additional details sounds like a good idea.

**Comment by bocops** [comment]
@andregasser Another thought: I believe you mentioned in a different discussion earlier that it would be sensible to support the recent Mastodon API version (4.x) and the one before it (3.x). Since this was removed in Mastodon API 3.0.0, we should be safe to remove it.

Should we codify this decision about supported APIs somewhere - and if so, where?

**Comment by andregasser** [comment]
I think the best place at the moment would be API.md. I am currently creating an overview there, of what endpoints bigbone supports. But we could also easily add another section there.
