### ISSUE TITLE
Refactor Streaming API

### ISSUE THREAD

**Issue by andregasser** [andregasser/bigbone#87]
By looking at the code, I can see a lot of code duplication. Would be cool, if we could clean that up somehow.

**Comment by bocops** [comment]
Refactoring should include proper Kdoc, which I've now skipped for this class in #115.

**Comment by bocops** [comment]
Refactoring should ensure that response bodies are always closed. Note that this doesn't automatically happen by accessing `response.body?.byteStream()`.

**Comment by bocops** [comment]
I've had another look at how the whole Streaming API is documented. It is considerably different from the other methods, so perhaps we should deal with it differently:

We currently offer different methods, one each for streaming a different content source (public local/federated timeline, hashtag timeline, user [list] timeline), and the [streams we do not yet offer](https://docs.joinmastodon.org/methods/streaming/#streams) are all similar in that regard.

In each method, we receive one such stream and handle [all potential events/payloads](https://docs.joinmastodon.org/methods/streaming/#events). This necessarily leads to a crazy amount of code duplication, because each method basically does the same thing, just on a different endpoint.

We could factor out just the event handling part into its own method, but I wonder if it wouldn't be more straightforward to simply enumerate all possible streams, and then have one single method like:

`startStreaming(STREAM_TYPE, handler, id)`

with `STREAM_TYPE` being one of the enum constants and `id` being an optional String value that is interpreted as a hashtag name or list ID for those streams.

If we do this, it would be a breaking change for `3.0.0` instead of the minor update currently planned.

**Comment by andregasser** [comment]
Thanks for your thoughts on this! I need to have a closer look into this. Honestly, I did not spend too much time there yet. Will get back to you / this issue.
